config/routes.rb
Rails.application.routes.draw do

  get 'cucumbers/index'

  get 'cucumbers/show'

  get 'cucumbers/new'

  resources :cucumbers
  get 'cucumbers/:id/delete' => 'cucumbers#delete', :as => :cucumbers_delete

  get '/' => 'pages#home'
  'pages/erb_demo'

  get 'pages/render_demo' => 'pages/render_demo'
  get 'pages/redirect_demo' => 'pages/redirect_demo'

end

app/models/cucumber.rb
class Cucumber < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cucumbers_controller.rb
class CucumbersController < ApplicationController
  def index
    @cucumbers = Cucumber.all
  end

  def show
    @cucumber = Cucumber.find(params[:id])
  end

  def new
    @cucumber = Cucumber.new
  end

  def create
    @cucumber = Cucumber.new(cucumber_params)
    if @cucumber.save
      redirect_to(:action => 'index')
    else
      render('new')
    end
  end

  def cucumber_params
    params.require(:cucumber).permit(:browser, :env, :tag)
  end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end

  def erb_demo
  end

  def render_demo
    render :home
  end

  def redirect_demo
    redirect_to(:action => 'home')
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cucumbers_helper.rb
module CucumbersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/cucumbers/_form.html.erb
<%= form_for(@cucumber) do |f| %>

    <div class="browser">
      <%= f.label :browser %><br>
      <%= f.text_field :browser %>
    </div>

    <div class="env">
      <%= f.label :env %><br>
      <%= f.text_field :env %>
    </div>

    <div class="tag">
      <%= f.label :tag %><br>
      <%= f.text_field :tag %>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/cucumbers/index.html.erb
<div class="cucumbers">
  <div class="container">
    <div class="row">
      <div class="col-md-2">
        <h2>Cucumber Tests</h2>
      </div>
      <div class="col-md-8">
        <% @cucumbers.in_groups_of(3).each do |cucumbers| %>
            <% cucumbers.select! {|x| !x.nil?} %>
            <div class='row'>
              <% cucumbers.each do |cucumber| %>
                  <div class='col-md-4'>
                    <div class="env">
                      <img src= <%= cucumber.env %> >
                      <div class="caption">
                        <span class="listing-title"><%= cucumber.browser %></span>
                        <span><%= link_to 'Show', cucumber %></span>
                      </div>
                    </div>
                  </div>
              <% end %>
            </div>
        <% end %>

      </div>
    </div>

  </div>
</div>

<table>
  <thead>
  <tr>
    <th>Cucumber Test</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @cucumbers.each do |cucumber| %>
      <tr>
        <td><%= cucumber.browser %></td>
        <div class="env">
          <img src= <%=cucumber.env %> >
          <div>
            <td><%= link_to 'Show', cucumber %></td>
          </div>
        </div>
      </tr>
  <% end %>
  </tbody>
</table>
<br>

app/views/cucumbers/new.html.erb
<h1>New Cucumber Test</h1>

<%= render 'form' %>

<!--%= link_to 'Back', cucumber_path %>

app/views/cucumbers/show.html.erb
<h1>Cucumbers#show</h1>
<p>Find me in app/views/cucumbers/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Phantom</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/erb_demo.html.erb
<% "goodbye world" %>
<%= "hello world" %>

app/views/pages/home.html.erb
<div class="jumbotron">
  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <h1>Ref Tools</h1>
      </div>
    </div>
  </div>
</div>

<div class="trending">
  <div class="container">
    <h2>Features</h2>
    <div class="row trending-listing">
      <div class="col-md-4">
        <div class="thumbnail">
          <img src="http://bit.ly/1R8kaBz">
          <!--<div class="caption">-->
          <span class="listing-title">Run a test</span>
          <!--</div>-->
        </div>
      </div>
      <!--<div class="col-md-4">-->
        <!--<div class="thumbnail">-->
          <!--<img src="http://www.testinteligencia.net/image/repository/test1.jpg">-->
          <!--<div class="caption">-->
            <!--<span class="listing-title">Run a suite of tests</span>-->
          <!--</div>-->
        <!--</div>-->
      <!--</div>-->
      <div class="col-md-4">
        <div class="thumbnail">
          <img src="http://www.sputnik.com/resources/support/techsupport/reports-icon.png">
          <!--<div class="caption">-->
            <span class="listing-title">View Reports</span>
          <!--</div>-->
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/render_demo.html.erb
<%= "This is your render_demo template." %>